default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  database: mun_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: mun_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: mun_prod
  pool: 5
  timeout: 5000
